module.exports = {
    getBlogs: function() {
        return [
            {
                "@rid":"#33:12",
                "host":"example",
                "description":"New and improved??",
                "blogId":"The new blog ID",
                "createDate":"2015-05-22T00:22:37.607",
                "$$hashKey":"object:241"
            },
            {
                "@rid":"#33:1",
                "host":"example",
                "description":"sdgasdgag",
                "blogId":"asdga",
                "createDate":"2015-05-02T12:52:20.121",
                "out_HasPost":["#36:9","#36:10","#36:11"],
                "out_Own":[
                    {
                        "@rid":"#33:8",
                        "host":"example",
                        "description":"fgjdfgjdj",
                        "blogId":"hdfgjd",
                        "createDate":"2015-05-02T15:57:28.789",
                        "in_Own":["#33:1"],
                        "out_Own":[
                            {
                                "@rid":"#33:9",
                                "host":"example",
                                "description":"dfhsdfhsdf",
                                "blogId":"dgsdfhs",
                                "createDate":"2015-05-02T19:15:53.034",
                                "in_Own":["#33:8"],
                                "out_Own":[
                                    {
                                        "@rid":"#33:11",
                                        "host":"example",
                                        "description":"asdgasdg",
                                        "blogId":"sdfhsdfhs",
                                        "createDate":"2015-05-02T21:22:25.813",
                                        "in_Own":["#33:9"]
                                    }
                                ]
                            },
                            {
                                "@rid":"#33:10",
                                "host":"example",
                                "description":"dgasdgasdg",
                                "blogId":"asdsdfhgasdg",
                                "createDate":"2015-05-02T21:19:58.117",
                                "in_Own":["#33:8"]
                            }
                        ],
                        "blog":{
                            "@rid":"#33:1",
                            "host":"example",
                            "description":"sdgasdgag",
                            "blogId":"asdga",
                            "createDate":"2015-05-02T12:52:20.121",
                            "out_HasPost":["#36:9","#36:10","#36:11"]
                        }
                    }
                ],
                "$$hashKey":"object:242"
            },{
                "@rid":"#33:2",
                "host":"example",
                "description":"asdgasdg",
                "blogId":"asdgasdg",
                "createDate":"2015-05-02T12:52:23.067",
                "$$hashKey":"object:243"
            },{
                "@rid":"#33:3",
                "host":"example",
                "description":"sdgasdga",
                "blogId":"asdgasdga",
                "createDate":"2015-05-02T12:52:25.675",
                "$$hashKey":"object:244"
            },{
                "@rid":"#33:7",
                "host":"example",
                "description":"dfgjdfgjdj",
                "blogId":"dfgjdfgjdfgj",
                "createDate":"2015-05-02T12:52:43.251",
                "$$hashKey":"object:245"
            },{
                "@rid":"#33:5",
                "host":"example",
                "description":"jfdgdfjhdfgjh",
                "blogId":"dfgjdsdfsdfh",
                "createDate":"2015-05-02T12:52:36.714",
                "$$hashKey":"object:246"
            }
        ];
    },

    getBlogPosts: function() {
        return [
            {
                "createUserId":"stevehu",
                "postId":"GT3ZmMIxTxiE8WzGudooQA",
                "createRid":"#14:0",
                "rid":"#36:11",
                "title":"TEst",
                "content":"This is the post - Edited -5/21/2015",
                "parentId":"asdga",
                "createDate":"2015-05-02T14:20:13.512"
            },{
                "createUserId":"stevehu",
                    "postId":"uGRKOudDR4e3EGwrNYi6cQ",
                    "createRid":"#14:0",
                    "rid":"#36:10",
                    "title":"jdfgjdfgjd",
                    "content":"fgjdfgj",
                    "parentId":"asdga",
                    "createDate":"2015-05-02T12:57:12.315"
            },{
                "createUserId":"stevehu",
                    "postId":"FY4pUJ1CSzSURhihDlLg5g",
                    "createRid":"#14:0",
                    "rid":"#36:9",
                    "title":"sdfhsdfhsdf",
                    "content":"hsdfhsdfhsdf",
                    "parentId":"asdga",
                    "createDate":"2015-05-02T12:55:51.351"
            }
        ];
    },
    getPost: function() {
        return {
            "createUserId":"stevehu",
            "postId":"GT3ZmMIxTxiE8WzGudooQA",
            "createRid":"#14:0",
            "rid":"#36:11",
            "title":"TEst",
            "content":"This is the post - Edited -5/21/2015",
            "parentId":"asdga",
            "createDate":"2015-05-02T14:20:13.512"
        };
    },
    init: function() {
        localStorage.clear();
        localStorage.setItem('blogs', JSON.stringify([
            {
                "@rid":"#33:12",
                "host":"example",
                "description":"New and improved??",
                "blogId":"The new blog ID",
                "createDate":"2015-05-22T00:22:37.607",
                "$$hashKey":"object:241"
            },
            {
                "@rid":"#33:1",
                "host":"example",
                "description":"sdgasdgag",
                "blogId":"asdga",
                "createDate":"2015-05-02T12:52:20.121",
                "out_HasPost":["#36:9","#36:10","#36:11"],
                "out_Own":[
                    {
                        "@rid":"#33:8",
                        "host":"example",
                        "description":"fgjdfgjdj",
                        "blogId":"hdfgjd",
                        "createDate":"2015-05-02T15:57:28.789",
                        "in_Own":["#33:1"],
                        "out_Own":[
                            {
                                "@rid":"#33:9",
                                "host":"example",
                                "description":"dfhsdfhsdf",
                                "blogId":"dgsdfhs",
                                "createDate":"2015-05-02T19:15:53.034",
                                "in_Own":["#33:8"],
                                "out_Own":[
                                    {
                                        "@rid":"#33:11",
                                        "host":"example",
                                        "description":"asdgasdg",
                                        "blogId":"sdfhsdfhs",
                                        "createDate":"2015-05-02T21:22:25.813",
                                        "in_Own":["#33:9"]
                                    }
                                ]
                            },
                            {
                                "@rid":"#33:10",
                                "host":"example",
                                "description":"dgasdgasdg",
                                "blogId":"asdsdfhgasdg",
                                "createDate":"2015-05-02T21:19:58.117",
                                "in_Own":["#33:8"]
                            }
                        ],
                        "blog":{
                            "@rid":"#33:1",
                            "host":"example",
                            "description":"sdgasdgag",
                            "blogId":"asdga",
                            "createDate":"2015-05-02T12:52:20.121",
                            "out_HasPost":["#36:9","#36:10","#36:11"]
                        }
                    }
                ],
                "$$hashKey":"object:242"
            },{
                "@rid":"#33:2",
                "host":"example",
                "description":"asdgasdg",
                "blogId":"asdgasdg",
                "createDate":"2015-05-02T12:52:23.067",
                "$$hashKey":"object:243"
            },{
                "@rid":"#33:3",
                "host":"example",
                "description":"sdgasdga",
                "blogId":"asdgasdga",
                "createDate":"2015-05-02T12:52:25.675",
                "$$hashKey":"object:244"
            },{
                "@rid":"#33:7",
                "host":"example",
                "description":"dfgjdfgjdj",
                "blogId":"dfgjdfgjdfgj",
                "createDate":"2015-05-02T12:52:43.251",
                "$$hashKey":"object:245"
            },{
                "@rid":"#33:5",
                "host":"example",
                "description":"jfdgdfjhdfgjh",
                "blogId":"dfgjdsdfsdfh",
                "createDate":"2015-05-02T12:52:36.714",
                "$$hashKey":"object:246"
            }
        ]));
        localStorage.setItem('blogPosts', JSON.stringify([
            {
                "createUserId":"stevehu",
                "postId":"GT3ZmMIxTxiE8WzGudooQA",
                "createRid":"#14:0",
                "rid":"#36:11",
                "title":"TEst",
                "content":"This is the post - Edited -5/21/2015",
                "parentId":"asdga",
                "createDate":"2015-05-02T14:20:13.512"
            },{
                "createUserId":"stevehu",
                "postId":"uGRKOudDR4e3EGwrNYi6cQ",
                "createRid":"#14:0",
                "rid":"#36:10",
                "title":"jdfgjdfgjd",
                "content":"fgjdfgj",
                "parentId":"asdga",
                "createDate":"2015-05-02T12:57:12.315"
            },{
                "createUserId":"stevehu",
                "postId":"FY4pUJ1CSzSURhihDlLg5g",
                "createRid":"#14:0",
                "rid":"#36:9",
                "title":"sdfhsdfhsdf",
                "content":"hsdfhsdfhsdf",
                "parentId":"asdga",
                "createDate":"2015-05-02T12:55:51.351"
            }
        ]));
        return JSON.parse(localStorage.getItem('blogs'));
    }
};